name: test-workflow.yml
on:
  push:
jobs:
  release-notes:
    name: Publish release notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          scripts/get-pr-release-notes.sh "1" "release-notes.md"